# Relatórios de cliques e vendas

In [4]:
import pandas as pd

path_erp_vendas = "./dados/erp_vendas.csv"
path_relatorio_marketing = "./dados/relatorio_marketing.csv"
df_erp_vendas = pd.read_csv(path_erp_vendas)
df_relatorio_marketing = pd.read_csv(path_relatorio_marketing)

In [5]:
df_erp_vendas.head(7)

,id_pedido,data_venda,produto,valor_real,metodo_pagamento,status_pagamento
0,1001,2026-04-10,Cadeira Gamer RGB,899.9,PIX,Pago
1,1002,2026-04-10,Sofá 3 Lugares,1500.0,Boleto,Cancelado
2,1003,2026-04-11,Cadeira Gamer RGB,899.9,Cartao,Pago
3,1004,2026-04-12,Mesa de Vidro 6 Lugares,1890.0,PIX,Pago
4,1006,2026-04-14,Estante TV 65,450.0,Cartao,Estornado
5,1007,2026-04-15,Poltrona do Papai,799.0,PIX,Pago

In [6]:
df_erp_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_pedido         6 non-null      int64
 1   data_venda        6 non-null      str
 2   produto           6 non-null      str
 3   valor_real        6 non-null      float64
 4   metodo_pagamento  6 non-null      str
 5   status_pagamento  6 non-null      str
dtypes: float64(1), int64(1), str(4)
memory usage: 420.0 bytes

In [7]:
df_relatorio_marketing.head(7)

,id_transacao,data,campanha,produto,valor_conversao,status
0,TRX-1001,2026-04-10,Cadeira_Gamer_Promo,Cadeira Gamer RGB,899.9,Aprovado
1,TRX-1002,2026-04-10,Sofa_Retratil_Lancamento,Sofá 3 Lugares,1500.0,Aprovado
2,TRX-1003,2026-04-11,Cadeira_Gamer_Promo,Cadeira Gamer RGB,899.9,Aprovado
3,TRX-1003,2026-04-11,Cadeira_Gamer_Promo,Cadeira Gamer RGB,899.9,Aprovado
4,TRX-1004,2026-04-12,Mesa_Jantar_Premium,Mesa de Vidro 6 Lugares,2100.0,Aprovado
5,TRX-1005,2026-04-13,Sofa_Retratil_Lancamento,Sofá 3 Lugares,1500.0,Aprovado
6,TRX-1006,2026-04-14,Estante_Home_Sale,Estante TV 65,450.0,Aprovado

In [8]:
df_relatorio_marketing.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_transacao     7 non-null      str
 1   data             7 non-null      str
 2   campanha         7 non-null      str
 3   produto          7 non-null      str
 4   valor_conversao  7 non-null      float64
 5   status           7 non-null      str
dtypes: float64(1), str(5)
memory usage: 468.0 bytes

# Ajuste dType Column "data"

In [9]:
#df_erp_vendas['data_venda'] = df_erp_vendas['data_venda'].astype('datetime64[ns]')
df_erp_vendas['data_venda'] = pd.to_datetime(df_erp_vendas['data_venda'], errors='coerce')

#df_relatorio_marketing['data'] = df_relatorio_marketing['data'].astype('datetime64[ns]')
df_relatorio_marketing['data'] = pd.to_datetime(df_relatorio_marketing['data'], errors='coerce')

In [10]:
df_erp_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_pedido         6 non-null      int64
 1   data_venda        6 non-null      datetime64[us]
 2   produto           6 non-null      str
 3   valor_real        6 non-null      float64
 4   metodo_pagamento  6 non-null      str
 5   status_pagamento  6 non-null      str
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 420.0 bytes

In [11]:
df_relatorio_marketing.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_transacao     7 non-null      str
 1   data             7 non-null      datetime64[us]
 2   campanha         7 non-null      str
 3   produto          7 non-null      str
 4   valor_conversao  7 non-null      float64
 5   status           7 non-null      str
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 468.0 bytes

# Fixing key before merge

In [12]:
df_relatorio_marketing['id_transacao'] = df_relatorio_marketing['id_transacao'].str.replace('TRX-','').astype('int64')
df_relatorio_marketing.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_transacao     7 non-null      int64
 1   data             7 non-null      datetime64[us]
 2   campanha         7 non-null      str
 3   produto          7 non-null      str
 4   valor_conversao  7 non-null      float64
 5   status           7 non-null      str
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 468.0 bytes

# Merging dfs

In [13]:
df_erp_vendas.head(7)

,id_pedido,data_venda,produto,valor_real,metodo_pagamento,status_pagamento
0,1001,2026-04-10,Cadeira Gamer RGB,899.9,PIX,Pago
1,1002,2026-04-10,Sofá 3 Lugares,1500.0,Boleto,Cancelado
2,1003,2026-04-11,Cadeira Gamer RGB,899.9,Cartao,Pago
3,1004,2026-04-12,Mesa de Vidro 6 Lugares,1890.0,PIX,Pago
4,1006,2026-04-14,Estante TV 65,450.0,Cartao,Estornado
5,1007,2026-04-15,Poltrona do Papai,799.0,PIX,Pago

In [14]:
df_relatorio_marketing.head(7)

,id_transacao,data,campanha,produto,valor_conversao,status
0,1001,2026-04-10,Cadeira_Gamer_Promo,Cadeira Gamer RGB,899.9,Aprovado
1,1002,2026-04-10,Sofa_Retratil_Lancamento,Sofá 3 Lugares,1500.0,Aprovado
2,1003,2026-04-11,Cadeira_Gamer_Promo,Cadeira Gamer RGB,899.9,Aprovado
3,1003,2026-04-11,Cadeira_Gamer_Promo,Cadeira Gamer RGB,899.9,Aprovado
4,1004,2026-04-12,Mesa_Jantar_Premium,Mesa de Vidro 6 Lugares,2100.0,Aprovado
5,1005,2026-04-13,Sofa_Retratil_Lancamento,Sofá 3 Lugares,1500.0,Aprovado
6,1006,2026-04-14,Estante_Home_Sale,Estante TV 65,450.0,Aprovado

In [15]:
#df_erp_vendas['data_venda'] = df_erp_vendas['data_venda'].astype('datetime64[ns]')
df_erp_vendas['data_venda'] = pd.to_datetime(df_erp_vendas['data_venda'], errors='coerce')

#df_relatorio_marketing['data'] = df_relatorio_marketing['data'].astype('datetime64[ns]')
df_relatorio_marketing['data'] = pd.to_datetime(df_relatorio_marketing['data'], errors='coerce')

In [16]:
df_compare_erp_relatorio = pd.merge(
    df_erp_vendas, 
    df_relatorio_marketing, 
    left_on='id_pedido', 
    right_on='id_transacao', 
    how='outer', 
    suffixes=("_erp", "_mkt")
)
 
df_compare_erp_relatorio

,id_pedido,data_venda,produto_erp,valor_real,metodo_pagamento,status_pagamento,id_transacao,data,campanha,produto_mkt,valor_conversao,status
0,1001.0,2026-04-10,Cadeira Gamer RGB,899.9,PIX,Pago,1001.0,2026-04-10,Cadeira_Gamer_Promo,Cadeira Gamer RGB,899.9,Aprovado
1,1002.0,2026-04-10,Sofá 3 Lugares,1500.0,Boleto,Cancelado,1002.0,2026-04-10,Sofa_Retratil_Lancamento,Sofá 3 Lugares,1500.0,Aprovado
2,1003.0,2026-04-11,Cadeira Gamer RGB,899.9,Cartao,Pago,1003.0,2026-04-11,Cadeira_Gamer_Promo,Cadeira Gamer RGB,899.9,Aprovado
3,1003.0,2026-04-11,Cadeira Gamer RGB,899.9,Cartao,Pago,1003.0,2026-04-11,Cadeira_Gamer_Promo,Cadeira Gamer RGB,899.9,Aprovado
4,1004.0,2026-04-12,Mesa de Vidro 6 Lugares,1890.0,PIX,Pago,1004.0,2026-04-12,Mesa_Jantar_Premium,Mesa de Vidro 6 Lugares,2100.0,Aprovado
5,NaN,NaT,NaN,NaN,NaN,NaN,1005.0,2026-04-13,Sofa_Retratil_Lancamento,Sofá 3 Lugares,1500.0,Aprovado
6,1006.0,2026-04-14,Estante TV 65,450.0,Cartao,Estornado,1006.0,2026-04-14,Estante_Home_Sale,Estante TV 65,450.0,Aprovado
7,1007.0,2026-04-15,Poltrona do Papai,799.0,PIX,Pago,NaN,NaT,NaN,NaN,NaN,NaN

In [17]:
df_compare_erp_relatorio.drop(columns='produto_mkt', inplace=True)

# Checking Empty IDs

In [18]:
df_id_pedido_nas = df_compare_erp_relatorio[df_compare_erp_relatorio["id_pedido"].isna()]
df_id_pedido_nas

,id_pedido,data_venda,produto_erp,valor_real,metodo_pagamento,status_pagamento,id_transacao,data,campanha,valor_conversao,status
5,NaN,NaT,NaN,NaN,NaN,NaN,1005.0,2026-04-13,Sofa_Retratil_Lancamento,1500.0,Aprovado

In [19]:
df_id_transacao_nas = df_compare_erp_relatorio[df_compare_erp_relatorio["id_transacao"].isna()]
df_id_transacao_nas

,id_pedido,data_venda,produto_erp,valor_real,metodo_pagamento,status_pagamento,id_transacao,data,campanha,valor_conversao,status
7,1007.0,2026-04-15,Poltrona do Papai,799.0,PIX,Pago,NaN,NaT,NaN,NaN,NaN

# Checking Payment Issue

In [20]:
is_status_pagamento_not_Pago = df_compare_erp_relatorio["status_pagamento"] != "Pago"
df_status_pagamento_payment_issue = df_compare_erp_relatorio[is_status_pagamento_not_Pago]
df_status_pagamento_payment_issue

,id_pedido,data_venda,produto_erp,valor_real,metodo_pagamento,status_pagamento,id_transacao,data,campanha,valor_conversao,status
1,1002.0,2026-04-10,Sofá 3 Lugares,1500.0,Boleto,Cancelado,1002.0,2026-04-10,Sofa_Retratil_Lancamento,1500.0,Aprovado
5,NaN,NaT,NaN,NaN,NaN,NaN,1005.0,2026-04-13,Sofa_Retratil_Lancamento,1500.0,Aprovado
6,1006.0,2026-04-14,Estante TV 65,450.0,Cartao,Estornado,1006.0,2026-04-14,Estante_Home_Sale,450.0,Aprovado

# Checking Price Issue

In [21]:
s_valor_real = df_compare_erp_relatorio["valor_real"]
s_valor_conversao = df_compare_erp_relatorio["valor_conversao"]
df_compare_s_valor_conversao = s_valor_real.compare( s_valor_conversao, result_names=("valor","conversao") )
df_compare_s_valor_conversao

    valor  conversao
4  1890.0     2100.0
5     NaN     1500.0
7   799.0        NaN

# Shortening price comparison

In [ ]:
mask_price_comparison = s_valor_real != s_valor_conversao

In [33]:
df_overview_issues = df_compare_erp_relatorio[ 
    (is_status_pagamento_not_Pago) 
    | 
    (s_valor_real != s_valor_conversao) 
]
df_overview_issues

,id_pedido,data_venda,produto_erp,valor_real,metodo_pagamento,status_pagamento,id_transacao,data,campanha,valor_conversao,status
1,1002.0,2026-04-10,Sofá 3 Lugares,1500.0,Boleto,Cancelado,1002.0,2026-04-10,Sofa_Retratil_Lancamento,1500.0,Aprovado
4,1004.0,2026-04-12,Mesa de Vidro 6 Lugares,1890.0,PIX,Pago,1004.0,2026-04-12,Mesa_Jantar_Premium,2100.0,Aprovado
5,NaN,NaT,NaN,NaN,NaN,NaN,1005.0,2026-04-13,Sofa_Retratil_Lancamento,1500.0,Aprovado
6,1006.0,2026-04-14,Estante TV 65,450.0,Cartao,Estornado,1006.0,2026-04-14,Estante_Home_Sale,450.0,Aprovado
7,1007.0,2026-04-15,Poltrona do Papai,799.0,PIX,Pago,NaN,NaT,NaN,NaN,NaN

In [ ]:
df_overview_issues.to_csv("./dados/relatorio_fraudes.csv")